---
- include_vars: splunkppassword.yml

- name: Create Splunk unix group
  group: name=splunkp
         state=present

- name: Create Splunk unix user
  user: name=splunkp
        group=splunkp
        state=present
        comment="Splunk User"
        shell="/bin/bash"
        home="/opt/splunk"
        password="{{ splunkp_password }}"

- name: Add authorized key to user splunkp
  authorized_key: user=splunkp
                  key="{{ shared_ssh_public_key }}"
                  state=present
